### ISSUE TITLE
Error after install 

### ISSUE THREAD

**Issue by rodrigoselau** [adroste/freepbx-realtime-calls-contacts-panel#1]
I installed your module but I got the following error:

Would you help me ?

 `[ERROR] Error: [Database] freepbx config does not include all required values: AMPDBUSER, AMPDBPASS, AMPDBHOST, AMPDBPORT, AMPDBNAME
    at parseFreepbxConf (/var/www/html/admin/modules/callpanel/calls-contacts-panel/src/database.ts:31:11)
    at /var/www/html/admin/modules/callpanel/calls-contacts-panel/src/database.ts:50:21
    at Generator.next (<anonymous>)
    at fulfilled (/var/www/html/admin/modules/callpanel/calls-contacts-panel/node_modules/tslib/tslib.js:114:62)
[15.07.2022 16:21.23.405] [ERROR] Error: [Database] freepbx config does not include all required values: AMPDBUSER, AMPDBPASS, AMPDBHOST, AMPDBPORT, AMPDBNAME
    at parseFreepbxConf (/var/www/html/admin/modules/callpanel/calls-contacts-panel/src/database.ts:31:11)
    at /var/www/html/admin/modules/callpanel/calls-contacts-panel/src/database.ts:50:21
    at Generator.next (<anonymous>)
    at fulfilled (/var/www/html/admin/modules/callpanel/calls-contacts-panel/node_modules/tslib/tslib.js:114:62)`

**Comment by adroste** [comment]
The module tries to read the database connection parameters from a freepbx config file.
The default location is: `/etc/freepbx.conf`. (Tested on FreePBX 16 on Raspberry Pi, installed with the RonR script)
Could you check, that (1) the file exists and (2) contains values for the keys: *'AMPDBUSER', 'AMPDBPASS', 'AMPDBHOST', 'AMPDBPORT', 'AMPDBNAME'* ?
